# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BugsnagReactNativeExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BugsnagReactNativeExample
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'


  target 'BugsnagReactNativeExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BugsnagReactNativeExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BugsnagReactNativeExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BugsnagReactNativeExample-tvOS

end
